/**
 * 接口API地址
 * add by zeke
 * add date 2018-05-10
 */
export default {
  weChatShare: '/api/weChat/weChatShare',
  getMemberInfo: '/shop/api.go?action=getMemberInfo',
  userLogin: '/shop/api.go?action=login',
  loginOut: '/shop/api.go?action=loginOut',
  userRegister: '/shop/api.go?action=register',
  sendSmsCode: '/shop/api.go?action=sendsms',
  imgFileUpload: '/shop/api.go?action=imageUpload',
  findLoginPwd: '/shop/api.go?action=findPwd',
  getPuCardTypes: '/shop/api.go?action=getPuCardTypes',
  getPuCardTradeRecord: '/shop/api.go?action=getPuCardTradeRecord',
  createOrder: '/shop/api.go?action=createOrder',
  uploadHeadPortrait: '/shop/api.go?action=uploadHeadPortrait',
  setLoginName: '/shop/api.go?action=setLoginName',
  setNickname: '/shop/api.go?action=setNickname',
  getAreas: '/shop/api.go?action=getAreas',
  getAreasByParentCode: '/shop/api.go?action=getAreasByParentCode',
  getMemberAddressList: '/shop/api.go?action=getMemberAddressList',
  getMemberAddress: '/shop/api.go?action=getMemberAddress',
  saveMemberAddress: '/shop/api.go?action=saveMemberAddress',
  deleteMemberAddress: '/shop/api.go?action=deleteMemberAddress',
  getMerchantList: '/shop/api.go?action=getMerchantList',
  getHomeBanner: '/shop/api.go?action=getHomeBanner',
  getMerchantInfo: '/shop/api.go?action=getMerchantInfo',
  getPuCardOrders: '/shop/api.go?action=getPuCardOrders',
  getPuCardOrderDetail: '/shop/api.go?action=getPuCardOrderDetail',
  activationPuCard: '/shop/api.go?action=activationPuCard',
  activationPuCardImpl: '/shop/api.go?action=activationPuCardImpl',
  myPuCards: '/shop/api.go?action=myPuCards',
  getCommodityList: '/shop/api.go?action=getCommodityList',
  getCommodityInfo: '/shop/api.go?action=getCommodityInfo',
  getOrderCommodity: '/shop/api.go?action=getOrderCommodity',
  cancelOrder: '/shop/api.go?action=cancelOrder',
  deleteOrder: '/shop/api.go?action=deleteOrder',
  buyerConfirmOrder: '/shop/api.go?action=buyerConfirmOrder',
  orderPay: '/shop/api.go?action=orderPay',
  queryMessage: '/shop/api.go?action=queryMessage',
  queryProducts: '/shop/api.go?action=queryProducts',
  alipayH5: '/shop/api.go?action=alipayH5',
  addCollection: '/shop/api.go?action=addCollection',
  myFavorite: '/shop/api.go?action=myFavorite'
};