/**
 * 接口API地址
 * add by zeke
 * add date 2018-05-10
 */
export default {
  weChatShare: '/api/weChat/weChatShare',
  getMemberInfo: '/shop/api.go?action=getMemberInfo',
  userLogin: '/shop/api.go?action=login',
  loginOut: '/shop/api.go?action=loginOut',
  userRegister: '/shop/api.go?action=register',
  sendSmsCode: '/shop/api.go?action=sendsms',
  imgFileUpload: '/shop/api.go?action=imageUpload',
  findLoginPwd: '/shop/api.go?action=findPwd',
  getPuCardTypes: '/shop/api.go?action=getPuCardTypes',
  getPuCardTradeRecord: '/shop/api.go?action=getPuCardTradeRecord',
  createOrder: '/shop/api.go?action=createOrder',
  uploadHeadPortrait: '/shop/api.go?action=uploadHeadPortrait',
  setLoginName: '/shop/api.go?action=setLoginName',
  setNickname: '/shop/api.go?action=setNickname',
  getAreas: '/shop/api.go?action=getAreas',
  getAreasByParentCode: '/shop/api.go?action=getAreasByParentCode',
  getMemberAddressList: '/shop/api.go?action=getMemberAddressList',
  getMemberAddress: '/shop/api.go?action=getMemberAddress',
  saveMemberAddress: '/shop/api.go?action=saveMemberAddress',
  deleteMemberAddress: '/shop/api.go?action=deleteMemberAddress',
  getMerchantList: '/shop/api.go?action=getMerchantList',
  getHomeBanner: '/shop/api.go?action=getHomeBanner',
  getMerchantInfo: '/shop/api.go?action=getMerchantInfo',
  getPuCardOrders: '/shop/api.go?action=getPuCardOrders',
  getPuCardOrderDetail: '/shop/api.go?action=getPuCardOrderDetail',
  activationPuCard: '/shop/api.go?action=activationPuCard',
  activationPuCardImpl: '/shop/api.go?action=activationPuCardImpl',
  myPuCards: '/shop/api.go?action=myPuCards',
  getCommodityList: '/shop/api.go?action=getCommodityList',
  getCommodityInfo: '/shop/api.go?action=getCommodityInfo',
  getOrderCommodity: '/shop/api.go?action=getOrderCommodity',
  cancelOrder: '/shop/api.go?action=cancelOrder',
  deleteOrder: '/shop/api.go?action=deleteOrder',
  buyerConfirmOrder: '/shop/api.go?action=buyerConfirmOrder',
  orderPay: '/shop/api.go?action=orderPay',
  queryMessage: '/shop/api.go?action=queryMessage',
  queryProducts: '/shop/api.go?action=queryProducts',
  alipayH5: '/shop/api.go?action=alipayH5',
  addCollection: '/shop/api.go?action=addCollection',
  myFavorite: '/shop/api.go?action=myFavorite',
  orderComment: '/shop/api.go?action=orderComment',
  getMerchCommens:'/shop/api.go?action=getMerchCommens',
  getCommodityCommens:'/shop/api.go?action=getCommodityCommens',
  getCalcForceServices:'/shop/api.go?action=getCalcForceServices',
  getCalcForceIncomes:'/shop/api.go?action=getCalcForceIncomes',
  confirmPayment:'/shop/api.go?action=confirmPayment',
  getsystemMessagges:'/shop/api.go?action=getsystemMessagges',
  getPucardBalance:'/shop/api.go?action=getPucardBalance',
  resetPayPwd:'/shop/api.go?action=resetPayPwd',
  weixinpayH5: '/shop/api.go?action=weixinpayH5',
  getWeixinCode:'/shop/api.go?action=getWeixinCode',
  getSourceWalletVersion:'/shop/api.go?action=getSourceWalletVersion',
  getInvitationCode:'/shop/api.go?action=getInvitationCode',
  getMemberInvitRegister:'/shop/api.go?action=getMemberInvitRegister',
  shareCommodity:'/shop/api.go?action=shareCommodity',
  myShares:'/shop/api.go?action=myShares',
  shareConfig:'/shop/api.go?action=shareConfig',
  shareCommodityOrders:'/shop/api.go?action=shareCommodityOrders',
  buildInvitationCode:'/shop/api.go?action=buildInvitationCode',
  weixinWalletMapSave:'/shop/api.go?action=weixinWalletMapSave',
  getScareBuyings:'/shop/api.go?action=getScareBuyings',
  getScareBuyingInfo:'/shop/api.go?action=getScareBuyingInfo',
  getActivityRemindConfigs:'/shop/api.go?action=getActivityRemindConfigs',
  sendWalletBstk:'/shop/api.go?action=sendWalletBstk',
  getWalletBill:'/shop/api.go?action=getWalletBill',
  getWalletBillDetail:'/shop/api.go?action=getWalletBillDetail',
  getWalletAddress:'/shop/api.go?action=getWalletAddress',
  saveMemberRemind:'/shop/api.go?action=saveMemberRemind',
  cancelMemberRemind:'/shop/api.go?action=cancelMemberRemind',
  saveActivitySubscribe:'/shop/api.go?action=saveActivitySubscribe',
  getAuction:'/shop/api.go?action=getAuction',
  getAuctionInfo:'/shop/api.go?action=getAuctionInfo',
  getMemberReminds:'/shop/api.go?action=getMemberReminds',
  auctionBid:'/shop/api.go?action=auctionBid',
  mySubcribe:'/shop/api.go?action=mySubcribe',
  getActivitysByMember:'/shop/api.go?action=getActivitysByMember',
  createScareBuyingOrder:'/shop/api.go?action=createScareBuyingOrder',
  getSysConfig:'/shop/api.go?action=getSysConfig',
  scareBuyingOrderPay:'/shop/api.go?action=scareBuyingOrderPay',
  getAuctionBidRecords:'/shop/api.go?action=getAuctionBidRecords',
  auctionOrderPay:'/shop/api.go?action=auctionOrderPay'
};